# SPDX-FileCopyrightText: 2023 Kevin de Jong <monkaii@hotmail.com>
# SPDX-License-Identifier: CC0-1.0

repos:
- repo: https://github.com/dev-build-deploy/commit-me
  rev: v0.12.2
  hooks:
  - id: commit-me

- repo: https://github.com/dev-build-deploy/reuse-me
  rev: v0.9.0
  hooks:
  - id: reuse-me
