# SPDX-FileCopyrightText: 2023 Kevin de Jong <monkaii@hotmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: 'ReleaseMe - GitHub Release Management'
author: 'Kevin de Jong'
description: >
  Managing GitHub releases using Conventional Commits.

branding:
  icon: 'code'  
  color: 'white'

inputs:
  token: 
    description: 'GitHub token used to access GitHub (eg. github.token)'
    required: false
  
  prefix:
    description: 'Prefix used for the release (eg. v)'
    required: false
  
  config:
    description: 'Path to the Release configuration file, defaults to .github/release.yml'
    required: false
    default: '.github/release.yml'
  
  artifacts:
    description: 'Artifact names to include in the GitHub Release'
    required: false
  
  files:
    description: 'Files to include in the GitHub Release'
    required: false

outputs:
  created:
    description: 'Boolean indicating if a release was created'

  release:
    description: 'JSON object containing the release information'

runs:
  using: 'node16'
  main: 'lib/index.js'
