# SPDX-FileCopyrightText: 2023 Kevin de Jong <monkaii@hotmail.com>
# SPDX-License-Identifier: CC0-1.0

name: 'ReleaseMe - GitHub Release Management'
author: 'Kevin de Jong'
description: >
  Managing GitHub releases using Conventional Commits.

branding:
  icon: 'code'  
  color: 'white'

inputs:
  token: 
    description: 'GitHub token used to access GitHub (eg. github.token)'
    required: false
  
  prefix:
    description: 'Prefix used for the version (eg. v)'
    required: false
  
  config:
    description: 'Path to the Release configuration file, defaults to .github/release.yml'
    required: false
    default: '.github/release.yml'
  
  artifacts:
    description: 'Multiline list of artifact names, uploaded as part of the current workflow run, to upload as a GitHub Release asset'
    required: false
  
  files:
    description: 'Multiline list of files (paths) to upload as a GitHub Release asset'
    required: false
  
  versioning:
    description: Versioning scheme to apply
    required: false
    default: 'semver'

  draft:
    description: 'Draft GitHub Release instead of publishing it'
    required: false
    default: false
  
  release-notes:
    description: 'External Release Notes file to include in the GitHub Release'
    required: false

  increment-type:
    description: 'Increment type to apply to the version'
    required: false
  
  version:
    description: 'Version to associate with the GitHub Release'
    required: false
  
  create-release:
    description: 'Create the GitHub Release, can be set to `false` to perform a dry run (i.e. determine the previous and incremented version)'
    required: false
    default: true

outputs:
  created:
    description: 'Boolean indicating if a release was created'

  release:
    description: 'JSON object containing the release information'

runs:
  using: 'node16'
  main: 'lib/main/index.js'
