# SPDX-FileCopyrightText: 2023 Kevin de Jong <monkaii@hotmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: 'ReleaseMe - GitHub Release Management'
author: 'Kevin de Jong'
description: >
  Managing GitHub releases using Conventional Commits.

branding:
  icon: 'code'  
  color: 'white'

inputs:
  token: 
    description: 'GitHub token used to access GitHub (eg. github.token)'
    required: false

outputs:
  created:
    description: 'Boolean indicating if a release was created'

  release:
    description: 'JSON object containing the release information'

runs:
  using: 'node16'
  main: 'lib/index.js'
