# SPDX-FileCopyrightText: 2023 Kevin de Jong <monkaii@hotmail.com>
# SPDX-License-Identifier: CC0-1.0

name: 'ReleaseMe - Update GitHub Release Assets'
author: 'Kevin de Jong'
description: >
  Uploads (or updates) assets to a GitHub Release.

branding:
  icon: 'code'  
  color: 'white'

inputs:
  token: 
    description: 'GitHub token used to access GitHub (eg. github.token)'
    required: false
  
  artifacts:
    description: 'Multiline list of artifact names, uploaded as part of the current workflow run, to upload as a GitHub Release asset'
    required: false
  
  files:
    description: 'Multiline list of files (paths) to upload as a GitHub Release asset'
    required: false

  remove:
    description: 'Multiline list of GitHub Asset label to remove from the GitHub Release assets'
    required: false
  
  download:
    description: 'Multiline list of GitHub Asset labels to download from the GitHub Release'
    required: false
  
  release-id:
    description: 'Release ID associated with the GitHub Release to update'
    required: true

runs:
  using: 'node16'
  main: '../lib/assets/index.js'
