# SPDX-FileCopyrightText: 2023 Kevin de Jong <monkaii@hotmail.com>
#
# SPDX-License-Identifier: CC0-1.0

---

name: Release and Deploy GitHub Action

concurrency: deployment

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release-me:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run ReleaseMe
        id: release
        uses: ./
        with:
          token: ${{ github.token }}

      - if: ${{ steps.release.outputs.created }}
        run: echo ${{ fromJSON(steps.release.outputs.release).tag_name }}
